### ISSUE TITLE
Serious Performance issue from "Dangerous alternative prefix" BigWarnings

### ISSUE THREAD

**Issue by mezz** [jaredlll08/RecipeStages#2]
https://github.com/jaredlll08/RecipeStages/blob/a0fb6951bf9c573452ae45d1218f1a3d9361b360/src/main/java/com/blamejared/recipestages/handlers/Recipes.java#L151

By setting registry names on recipes with a mod prefix other than "recipestages", it triggers bajillions of BigWarnings that look like this:
```
[22:50:44] [main/WARN] [FML]: ****************************************
[22:50:44] [main/WARN] [FML]: * Dangerous alternative prefix `farmingforblockheads` for name `market`, expected `crafttweaker` invalid registry invocation/invalid name?
[22:50:44] [main/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
[22:50:44] [main/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
[22:50:44] [main/WARN] [FML]: *  at com.blamejared.recipestages.handlers.Recipes$ActionSetStage.apply(Recipes.java:151)
[22:50:44] [main/WARN] [FML]: *  at crafttweaker.runtime.CrTTweaker.apply(CrTTweaker.java:43)
[22:50:44] [main/WARN] [FML]: *  at crafttweaker.CraftTweakerAPI.apply(CraftTweakerAPI.java:126)
[22:50:44] [main/WARN] [FML]: *  at java.lang.Iterable.forEach(Unknown Source)...
[22:50:44] [main/WARN] [FML]: ****************************************
```

There are so many that it has a serious impact on performance when called, pausing the game:
![bigwarning2](https://user-images.githubusercontent.com/916092/33114004-a7dd73e4-cf0f-11e7-8a0b-26b34a402ead.png)

**Comment by jaredlll08** [comment]
What is that error even for? as far as I know, what I'm doing is the correct way to replace a recipe (without removing it and re-adding it...). When I add a recipe in modA called "moda:testrecipe", and then in modB I add a recipe called "moda:testrecipe", the recipe from modA is replaced (which is what I need in this instance), so if that is an intended feature, why give the warning?
